/**
 * 初始化国籍字典库
 */
delete from dict_country_code;

insert into dict_country_code(id, en_name,cn_name) values
('CHN','CHINA','中国'),
('ABW','ARUBA','阿鲁巴'),
('AFG','AFGHANISTAN','阿富汗'),
('AFT','FRENCH SOUTHERN TERRITORIES','法国'),
('AGO','ANGOLA','安哥拉'),
('AIA','ANGUILLA','安圭拉'),
('ALB','ALBANIA','阿尔巴尼亚'),
('AND','ANDORRA','安道尔'),
('ANT','NETHERLANDS ANTILLES','荷兰'),
('ARE','UNITED ARAB EMIRATES','阿联酋'),
('ARG','ARGENTINA','阿根廷'),
('ARM','ARMENIA','亚美尼亚'),
('ASM','AMERICAN SAMOA','萨摩亚'),
('ATA','ANTARCTICA','南极洲'),
('ATG','ANTIGUA AND BARBUDA','安提瓜和巴布达'),
('AUS','AUSTRALIA','澳大利亚'),
('AUT','AUSTRIA','奥地利'),
('AZE','AZERBAIJAN','阿塞拜疆'),
('BDI','BURUNDI','布隆迪'),
('BEL','BELGIUM','比利时'),
('BEN','BENIN','贝宁'),
('BFA','BURKINA FASO','布基纳法索'),
('BGD','BANGLADESH','孟加拉'),
('BGR','BULGARIA','保加利亚'),
('BHR','BAHRAIN','BAHRAIN'),
('BHS','BAHAMAS','巴哈马'),
('BIH','BOSNIA AND HERZEGOVINA','波黑'),
('BLR','BELARUS','白俄罗斯'),
('BLZ','BELIZE','伯利兹'),
('BMU','BERMUDA','百慕大'),
('BOL','BOLIVIA','玻利维亚'),
('BRA','BRAZIL','巴西'),
('BRB','BARBADOS','巴巴多斯岛'),
('BRN','BRUNEI DARUSSALAM',' 文莱达鲁萨兰国'),
('BTN','BHUTAN','不丹'),
('BVT','BOUVET ISLAND','布韦岛'),
('BWA','BOTSWANA','博兹瓦纳'),
('CAF','CENTRAL AFRICAN REPUBLIC','中非共和国'),
('CAN','CANADA','加拿大'),
('CCK','COCOS (KEELING) ISLANDS','科科斯群岛'),
('CHE','SWITZERLAND','瑞士'),
('CHL','CHILE','智利'),
('CIV','COTE DVOIRE','COTE DVOIRE'),
('CMR','CAMEROON','喀麦隆'),
('COD','CONGO THE DEMOCRATIC REPUBLIC OF THE','刚果共和国'),
('COG','CONGO','刚果'),
('COK','COOK ISLAND','库克群岛'),
('COL','COLOMBIA','哥伦比亚'),
('COM','COMOROS','科摩罗'),
('CPV','CAPE VERDE','佛得角'),
('CRI','COSTA RICA','哥斯达黎加'),
('CUB','CUBA','古巴'),
('CXR','CHRISTMAS ISLAND','圣诞岛'),
('CYM','CAYMAN ISLANDS','开曼群岛'),
('CYP','CYPRUS','塞浦路斯'),
('CZE','CZECH REPUBLIC ','捷克'),
('DEU','GERMANY','德国'),
('DJI','DJIBOUTI','吉布提'),
('DMA','DOMINICA','多米尼克'),
('DNK','DENMARK','丹麦'),
('DOM','DOMINICAN REPUBLIC','多米尼加'),
('DZA','ALGERIA','阿尔及利亚'),
('ECU','ECUADOR','厄瓜多尔'),
('EGY','EGYPT','埃及'),
('ERI','ERITREA','厄立特里亚'),
('ESH','WESTERN SAHARA','西撒哈拉'),
('ESP','SPAIN','西班牙'),
('EST','ESTONIA','爱沙尼亚'),
('ETH','ETHIOPIA','埃塞俄比亚'),
('FIN','FINLAND','芬兰'),
('FJI','FIJI','斐济'),
('FLK','FALKLAND ISLANDS (MALVINAS)','马尔维纳斯群岛'),
('FRA','FRANCE','法国'),
('FRO','FAROE ISLANDS','法罗群岛'),
('FSM','MICRONESIA FEDERATED STATES OF','密克罗尼西亚联邦'),
('GAB','GABON','加蓬'),
('GBR','UNITED KINGDOM','大不列颠'),
('GEO','GEORGIA','格鲁吉亚'),
('GHA','GHANA','加纳'),
('GIB','GIBRALTAR','直布罗陀'),
('GIN','GUINEA','几内亚'),
('GLP','GUADELOUPE','瓜德鲁普'),
('GMB','GAMBIA','冈比亚'),
('GNB','GUINEA-BISSAU','几内亚比绍'),
('GNQ','EQUATORIAL GUINEA','赤道几内亚'),
('GRC','GREECE','希腊'),
('GRD','GRENADA',' 格林纳达'),
('GRL','GREENLAND','格陵兰岛'),
('GTM','GUATEMALA','危地马拉'),
('GUF','FRENCH GUIANA','圭亚那'),
('GUM','GUAM','关岛'),
('GUY','GUYANA','圭亚那'),
('HKG','HONG KONG','香港'),
('HMD','HEARD ISLAND AND MCDONALD ISLANDS','麦克唐纳群岛'),
('HND','HONDURAS','洪都拉斯'),
('HRV','CROATIA','克罗地亚'),
('HTI','HAITI','海地'),
('HUN','HUNGARY','匈牙利'),
('IDN','INDONESIA','印尼'),
('IND','INDIA','印度'),
('IOT','BRITISH INDIAN OCEAN TERRITORY','印度洋领地'),
('IRL','IRELAND','爱尔兰'),
('IRN','IRAN ISLAMIC REPUBLIC OF','伊朗'),
('IRQ','IRAQ ','伊拉克'),
('ISL','ICELAND','冰岛'),
('ISR','ISRAEL','以色列'),
('ITA','ITALY','意大利'),
('JAM','JAMAICA','牙买加'),
('JOR','JORDAN','JORDAN'),
('JPN','JAPAN','日本'),
('KAZ','KAZAKSTAN','哈萨克斯坦'),
('KEN','KENYA','肯尼亚'),
('KGZ','KYRGYZSTAN','吉尔吉斯斯坦'),
('KHM','CAMBODIA','柬埔寨'),
('KIR','KIRIBATI','基里巴斯'),
('KNA','SAINT KITTS AND NEVIS','尼维斯岛'),
('KOR','KOREA REPUBLIC OF','韩国'),
('KWT','KUWAIT','科威特'),
('LAO','LAO PEOPLES DEMOCRATIC REPUBLIC','老挝'),
('LBN','LEBANNON','黎巴嫩'),
('LBR','LIBERIA','利比里亚'),
('LBY','LIBYAN ARAB JAMAHIRIYA','利比亚民众国'),
('LCA','SAINT LUCIA','圣卢西亚'),
('LIE','LIECHTENSTEIN','列支敦士登'),
('LKA','SRI LANKA','斯里兰卡'),
('LSO','LESOTHO','莱索托'),
('LTU','LITHUANIA','立陶宛'),
('LUX','LUXEMBOURG','卢森堡'),
('LVA','LATIVA','LATIVA'),
('MAC','MACAU','澳门'),
('MAR','MOROCCO','摩洛哥'),
('MCO','MONACO','摩纳哥'),
('MDA','MOLDOVA REPUBLIC OF','摩尔多瓦'),
('MDG','MADAGASCAR','马达加斯'),
('MDV','MALDIVES','马尔代夫'),
('MEX','MEXICO','墨西哥'),
('MHL','MARSHALL ISLANDS','马绍尔群岛'),
('MKD','MACEDONIA THE FORMER YUGOSLAV REPUBLIC OF','马其顿'),
('MLI','MALI','马里'),
('MLT','MALTA','马耳他'),
('MMR','MYANMAR','缅甸'),
('MNG','MONGOLIA','蒙古'),
('MNP','NORTHERN MARIANA ISLANDS','亚纳群岛'),
('MOZ','MOZAMBIQUE','莫桑比克'),
('MRT','MAURITANIA','毛利塔尼亚'),
('MSR','MONTSERRAT','蒙特塞拉特'),
('MTQ','MARTINIQUE','马提尼克岛'),
('MUS','MAURITUS','毛里求斯'),
('MWI','MALAWI','马拉维'),
('MYS','MALAYSIA','马来西亚'),
('MYT','MAYOTTE','马约特岛'),
('NAM','NAMIBIA','纳米比亚 '),
('NCL','NEW CALEDONIA','新喀里多尼亚'),
('NER','NIGER','尼日尔'),
('NFK','NORFOLK ISLAND','诺福克岛'),
('NGA','NIGERIA','尼日利亚'),
('NIC','NICARAGUA','尼加拉瓜'),
('NIU','NIUE','纽埃'),
('NLD','NETHERLANDS','荷兰'),
('NOR','NORWAY','挪威'),
('NPL','NEPAL','尼泊尔'),
('NRU','NAURU','瑙鲁'),
('NZL','NEW ZEALAND','新西兰'),
('OMN','OMAN','阿曼'),
('PAK','PAKISTAN','巴基斯坦'),
('PAN','PANAMA','巴拿马'),
('PCN','PITCAIRN','皮特凯恩'),
('PER','PERU','秘鲁'),
('PHL','PHILIPPINES','菲律宾'),
('PLW','PALAU','帕劳'),
('PNG','PAPUA NEW GUINEA','巴布亚新几内亚'),
('POL','POLAND','波兰'),
('PRI','PUERTO RICO','波多黎各'),
('PRK','KOREA DEMOCRATIC PEOPLE S REPUBLIC OF','朝鲜'),
('PRT','PORTUGAL','葡萄牙'),
('PRY','PARAGUAY','巴拉圭'),
('PYF','FRENCH POLYNESIA','FRENCH POLYNESIA'),
('QAT','QATAR','卡塔尔'),
('REU','REUNION','团聚'),
('ROM','ROMANIA','罗马尼亚'),
('RUS','RUSSIAN FEDERATION','俄罗斯联邦'),
('RWA','RWANDA','卢旺达'),
('SAU','SAUDI ARABIA','沙特阿拉伯'),
('SDN','SUDAN','苏丹'),
('SEN','SENEGAL','塞内加尔'),
('SGP','SINGAPORE','新加坡'),
('SGS','SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','南乔治亚和南三明治群岛'),
('SHN','SAINT HELENA','圣海伦娜'),
('SJM','SVALBARD AND JAN MAYEN','斯瓦尔巴特群岛'),
('SLB','SOLOMON ISLANDS','所罗门群岛'),
('SLE','SIERRA LEONE','塞拉利昂'),
('SLV','EL SALVADOR','萨尔瓦多'),
('SMR','SAN MARINO','圣马力诺'),
('SOM','SOMALIA','索马里'),
('SPM','SAINT PIERRE AND MIQUELON','圣皮埃尔和密克隆岛'),
('STP','SAO TOME AND PRINCIPE','圣多美'),
('SUR','SURINAME','苏里南'),
('SVK','SLOVAKIA','斯洛伐克'),
('SVN','SLOVENIA','斯洛文尼亚'),
('SWE','SWEDEN','瑞典'),
('SWZ','SWAZILAND','斯威士兰'),
('SYC','SEYCHELLES','塞舌尔'),
('SYR','SYRIAN ARAB REPUBLIC','叙利亚'),
('TCA','TURKS AND CAICOS ISLANDS','特克斯和凯科斯群岛'),
('TCD','CHAD','乍得'),
('TGO','TOGO','多哥'),
('THA','THAILAND','thailand'),
('TJK','TAJIKISTAN','塔吉克斯坦'),
('TKL','TOKELAU','托克劳'),
('TKM','TURKMENISTAN','土库曼斯坦'),
('TMP','EAST TIMOR','东帝汶'),
('TON','TONGA','汤加'),
('TTO','TRINIDAD AND TOBAGO','特立尼达和多巴哥'),
('TUN','TUNISIA','突尼斯'),
('TUR','TURKEY','火鸡'),
('TUV','TUVALU','图瓦卢'),
('TWN','TAIWAN PROVINCE OF CHINA','台湾'),
('TZA','TANZANIA UNITED REPUBLIC OF','坦桑尼亚'),
('UGA','UGANDA','乌干达'),
('UKR','UKRAINE','基辅酒店'),
('UMI','UNITED STATES MINOR OUTLYING ISLANDS','outlying群岛'),
('URY','URUGUAY','乌拉圭'),
('USA','UNITED STATES','美国'),
('UZB','UZBEKISTAN','乌兹别克斯坦'),
('VAT','HOLY SEE (VATICAN CITY STATE)','HOLY SEE'),
('VCT','SAINT VINCENT AND THE GRENADINES','圣文森特'),
('VEN','VENEZUELA','委内瑞拉'),
('VGB','VIRGIN ISLANDS BRITISH','维尔京群岛英国'),
('VIR','VIRGIN ISLANDS U.S.','维尔京群岛美国'),
('VNM','VIET NAM','越南'),
('VUT','VANUATU','瓦努阿图'),
('WLF','WALLIS AND FUTUNA','富图纳群岛'),
('WSM','SAMOA','萨摩亚'),
('YEM','YEMEN','也门'),
('YUG','YUGOSLAVIA','南斯拉夫'),
('ZAF','SOUTH AFRICA','南非'),
('ZMB','ZAMBIA','赞比亚'),
('ZWE','ZIMBABWE','津巴布韦');